export const CLASS_COLORS = {
    path: "#1a9850",
    separated: "#66bd63",
    buffered: "#a6d96a",
    lane: "#fee08b",
    quiet_street: "#d9ef8b",
    service: "#d9ef8b",
    sharrow: "#fdae61",
    moderate_street: "#f46d43",
    busy_street: "#d73027",
    unpaved: "#a6761d",
};
export const PROFILES = {
    young_kids: {
        id: "young_kids",
        label: "young kids",
        paceKmh: 8,
        mult: {
            path: 1,
            separated: 1,
            buffered: 2,
            lane: 3,
            quiet_street: 1.4,
            service: 2,
            sharrow: 6,
            moderate_street: 8,
            busy_street: 25,
            unpaved: 2,
        },
        busyLane: 10,
        busyBuffered: 6,
        penScale: 1,
    },
    older_kids: {
        id: "older_kids",
        label: "older kids",
        paceKmh: 11,
        mult: {
            path: 1,
            separated: 1,
            buffered: 1.5,
            lane: 2,
            quiet_street: 1.2,
            service: 1.6,
            sharrow: 3.5,
            moderate_street: 4,
            busy_street: 12,
            unpaved: 1.5,
        },
        busyLane: 5,
        busyBuffered: 3,
        penScale: 0.6,
    },
    solo: {
        id: "solo",
        label: "solo",
        paceKmh: 16,
        mult: {
            path: 1,
            separated: 1,
            buffered: 1.1,
            lane: 1.3,
            quiet_street: 1.1,
            service: 1.3,
            sharrow: 2,
            moderate_street: 2.5,
            busy_street: 6,
            unpaved: 1.2,
        },
        busyLane: 2.5,
        busyBuffered: 1.8,
        penScale: 0.3,
    },
};
